// GENERATED by scripts/import-mfds-names.ts. Do not edit by hand: every name
// here must come from 식약처's own data, and this file is how that is shown.
// Empty until the first import (it needs the data.go.kr key).

import type { MfdsName, MfdsSource } from './mfds-types.ts';

export const MFDS_SOURCE: MfdsSource | null = null;

export const MFDS_NAMES: readonly MfdsName[] = [];
