/**
 * Run with: npm run test:unit
 *
 * The rows are in the shape assumed for 식약처's approval data. The Korean in
 * them is made up (성분가, 성분나...), so nothing here passes for real names.
 */
import assert from 'node:assert/strict';
import test from 'node:test';

import { agreeNames, extractPairs, matchRxNorm, tableModule, type RxConcept } from './mfds-import.ts';

const row = (ko: string, en: string) => ({ ITEM_NAME: 'x', MAIN_ITEM_INGR: ko, MAIN_INGR_ENG: en });

test('pairs names only from single-ingredient products, without 식약처 codes', () => {
  const { pairs, combinations, unreadable } = extractPairs([
    row('[M000001]성분가', 'Alphazine'),
    row('[M000002]성분나|[M000003]성분다', 'Betazine/Gammazine'),
    row('성분라', ''),
    row('', 'Deltazine'),
  ]);
  assert.deepEqual(pairs, [{ ko: '성분가', en: 'Alphazine' }]);
  assert.equal(combinations, 1);
  assert.equal(unreadable, 2);
});

test('a comma inside a number is not a separator between ingredients', () => {
  const { pairs } = extractPairs([row('성분가 1,000단위', 'Alphazine 1,000 units')]);
  assert.equal(pairs.length, 1);
});

test('one Korean name per English name; spacing variants are one name; real disagreements are left out', () => {
  const { names, conflicts } = agreeNames([
    { ko: '성분가', en: 'Alphazine' },
    { ko: '성분 가', en: 'ALPHAZINE' },
    { ko: '성분가', en: 'alphazine' },
    { ko: '성분나', en: 'Betazine' },
    { ko: '성분다', en: 'Betazine' },
  ]);
  assert.deepEqual(names.get('alphazine'), { ko: '성분가', mfdsEn: 'Alphazine', products: 3 });
  assert.equal(names.has('betazine'), false);
  assert.deepEqual(conflicts, [{ en: 'betazine', ko: ['성분나', '성분다'] }]);
});

test('only an exact RxNorm ingredient is kept: a salt, or a near name, is left out', async () => {
  const names = new Map([
    ['alphazine', { ko: '성분가', mfdsEn: 'Alphazine', products: 2 }],
    ['alphazine hydrochloride', { ko: '성분가염산염', mfdsEn: 'Alphazine Hydrochloride', products: 1 }],
    ['betazine', { ko: '성분나', mfdsEn: 'Betazine', products: 1 }],
    ['gammazine', { ko: '성분다', mfdsEn: 'Gammazine', products: 1 }],
  ]);
  const rxnorm: Record<string, RxConcept> = {
    alphazine: { rxcui: '111', name: 'alphazine', tty: 'IN' },
    'alphazine hydrochloride': { rxcui: '112', name: 'alphazine hydrochloride', tty: 'PIN' },
    // RxNav's nearest name, not this one.
    betazine: { rxcui: '113', name: 'betazine sodium', tty: 'IN' },
  };
  const { table, notIngredient, unmatched } = await matchRxNorm(names, async (en) => rxnorm[en] ?? null);
  assert.deepEqual(table, [{ rxcui: '111', en: 'alphazine', ko: '성분가', mfdsEn: 'Alphazine', products: 2 }]);
  assert.deepEqual(notIngredient, [{ en: 'alphazine hydrochloride', tty: 'PIN' }]);
  assert.deepEqual(unmatched, ['betazine', 'gammazine']);
});

test('the generated module says where it came from, and is the table exactly', () => {
  const module = tableModule(
    [{ rxcui: '111', en: 'alphazine', ko: '성분가', mfdsEn: 'Alphazine', products: 2 }],
    { dataset: 'apis.data.go.kr/example', retrieved: '2026-10-01', rows: 5 }
  );
  assert.match(module, /^\/\/ GENERATED by scripts\/import-mfds-names\.ts/);
  assert.match(module, /MFDS_SOURCE: MfdsSource \| null = \{"dataset":"apis\.data\.go\.kr\/example","retrieved":"2026-10-01","rows":5\}/);
  assert.match(module, /\{"rxcui":"111","en":"alphazine","ko":"성분가","mfdsEn":"Alphazine","products":2\},/);
});
