// Expo's ambient types — the `.css` side-effect import in `constants/theme.ts`,
// among others. `expo-env.d.ts` provides the same reference, but it is
// generated by `expo start` and gitignored, so a fresh clone typechecked
// before the first start failed on `import '@/global.css'`.
/// <reference types="expo/types" />
